# Generated by Django 4.1 on 2022-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Called')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_tetx', models.TextField(verbose_name='Statiya')),
                ('date', models.DateTimeField(verbose_name='Data public')),
            ],
        ),
    ]
